### ISSUE TITLE
Сonflict with the Studio Library plugin

### ISSUE THREAD

**Issue by Sprite37529** [DreamWall-Animation/dwpicker#104]
Hi. There is a conflict with the Studio Library plugin. I am observing this problem in maya 2025.2

Before I open dwpicker, the Studio Library plugin is working correctly. I can use the cursor to select saved animations and poses. After opening dwpicker, I can't use the cursor to select these animations and poses.

Messages about importing plugins appear in the script editor. The first time you open dwpicker, a message appears about importing and activating Pyside:
```
>> PySide6 Maya version found. PySide2 remap activated.
``` 

When working with Studio Library, a message appears:
```
# TypeError: # 'PySide6.QtWidgets.QTreeWidget.itemAt' called with wrong argument types:
#   PySide6.QtWidgets.QTreeWidget.itemAt(QPointF)
# Supported signatures:
#   PySide6.QtWidgets.QTreeWidget.itemAt(PySide6.QtCore.QPoint)
  PySide6.QtWidgets.QTreeWidget.itemAt(int, int)
# Traceback (most recent call last):
#   File "C:\Users\Username\Documents\maya\scripts\studiolibrary-2.17.2\src\studiolibrary\widgets\itemswidget\treewidget.py", line 673, in mouseMoveEvent
#     ItemViewMixin.mouseMoveEvent(self, event)
#   File "C:\Users\Username\Documents\maya\scripts\studiolibrary-2.17.2\src\studiolibrary\widgets\itemswidget\itemviewmixin.py", line 193, in mouseMoveEvent
#     item = self.itemAt(event.pos())
#            ^^^^^^^^^^^^^^^^^^^^^^^^
# TypeError: # 'PySide6.QtWidgets.QTreeWidget.itemAt' called with wrong argument types:
#   PySide6.QtWidgets.QTreeWidget.itemAt(QPointF)
# Supported signatures:
#   PySide6.QtWidgets.QTreeWidget.itemAt(PySide6.QtCore.QPoint)
  PySide6.QtWidgets.QTreeWidget.itemAt(int, int)
``` 

https://github.com/user-attachments/assets/50a818d0-cca6-497f-8d3a-6f571c982778

Thank you for your work.

**Comment by luckylyk** [comment]
Ouch.
Yeah this require that we migrate officially to PySide6. But we still have old production at studio on old maya version. And lack of time to maintain 2 differents versions.
We are probably going to move in 2/3 months. 

Until that time, you can try this pull request made by @jdrese and already made a real migration to PySide6
https://github.com/DreamWall-Animation/dwpicker/tree/b1439253f1bf539b5d4bafdd37739594ca7045be

This should solve your issue.

**Comment by luckylyk** [comment]
That should be fixed in version 1.0.0 !!
