### ISSUE TITLE
Cant load picker, maya 2020.4

### ISSUE THREAD

**Issue by Whoami243** [DreamWall-Animation/dwpicker#110]
I´ve followed the steps, and watched youtube videos to verify if i was doing something wrong but there´s no way for me to make the picker work.

Once I execute
"import dwpicker
dwpicker.show()"

I get the following error : # Error: ImportError: file C:/Users/XXXXX/Documents/maya/scripts\dwpicker\designer\editor.py line 7: cannot import name clipboard # 
cmdScrollFieldExecuter -e -execute scriptEditorPanel1Window|scriptEditorPanel1|formLayout192|formLayout194|paneLayout8|paneLayout9|tabLayout6|formLayout213|cmdScrollFieldExecuter58;
// Result: scriptEditorPanel1Window|scriptEditorPanel1|formLayout192|formLayout194|paneLayout8|paneLayout9|tabLayout6|formLayout213|cmdScrollFieldExecuter58 // 
import dwpicker
dwpicker.show()
# Error: ImportError: file C:/Users/Submarine/Documents/maya/scripts\dwpicker\designer\editor.py line 7: cannot import name clipboard #

**Comment by Whoami243** [comment]
// Result: scriptEditorPanel1Window|scriptEditorPanel1|formLayout192|formLayout194|paneLayout8|cmdScrollFieldReporter3 // 
cmdScrollFieldExecuter -e -execute scriptEditorPanel1Window|scriptEditorPanel1|formLayout192|formLayout194|paneLayout8|paneLayout9|tabLayout6|formLayout213|cmdScrollFieldExecuter58;
// Result: scriptEditorPanel1Window|scriptEditorPanel1|formLayout192|formLayout194|paneLayout8|paneLayout9|tabLayout6|formLayout213|cmdScrollFieldExecuter58 // 
import dwpicker
dwpicker.show()
# Error: cannot import name clipboard
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "C:/Users/XXXXX/Documents/maya/2020/scripts\dwpicker\__init__.py", line 17, in <module>
#     from dwpicker.main import DwPicker, WINDOW_CONTROL_NAME
#   File "C:/Users/XXXXX/Documents/maya/2020/scripts\dwpicker\main.py", line 15, in <module>
#     from dwpicker.designer.editor import PickerEditor
#   File "C:/Users/XXXXX/Documents/maya/scripts\dwpicker\designer\editor.py", line 7, in <module>
#     from dwpicker import clipboard
# ImportError: cannot import name clipboard #

**Comment by luckylyk** [comment]
Hi, can you ensure you are well using latest version of the picker ?
I'm not able to reproduce this issue.
Do you have any specific plugin running with Maya ?

**Comment by Whoami243** [comment]
Yea, im using the last version. No pluggins running, just animbot

**Comment by luckylyk** [comment]
I'm sorry, 'im a bit clueless reading you error. I just made a little update expecting it could helps.
Unfortunately I assume it is something due to your "language" configuration or maya version. I have no access to Maya 2020 anymore to test. Maybe update to a version 22 or + could helps ?

**Comment by luckylyk** [comment]
Hi sorry,
only back from vacation. I made some update.
Is this still not working with latest versions ?

**Comment by luckylyk** [comment]
without reply i'm closing the ticket. Feel free to reopen if you have any new for me ?
