### ISSUE TITLE
Error clicking in the picker window

### ISSUE THREAD

**Issue by carlosgmanimacion** [DreamWall-Animation/dwpicker#112]
Hi, I have this error when I click in the picker (I can't select anything in the picker, but when I click in any rig control, the picker detect that):

# Traceback (most recent call last):
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\picker.py", line 136, in mousePressEvent
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\picker.py", line 61, in detect_hovered_shape
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\interactive.py", line 177, in is_interactive
# KeyError: 'action.right'

**Comment by luckylyk** [comment]
Hi Carlos,
This is an old Picker version, could you please update first and tell me if is still happening ?

**Comment by carlosgmanimacion** [comment]
It's still happening, but I think i'm downloading the lastest version. How I can download the lastest version?

**Comment by luckylyk** [comment]
![Screenshot_20241217-182616](https://github.com/user-attachments/assets/b54c0306-8a5f-43c0-9a8b-7cd9b8bdcba9)
You should be able to reach out the latest version here

**Comment by carlosgmanimacion** [comment]
It's weird, because this is how I'm downloading the file. Now I have this other problem to import the picker.
![Maya Python Screenshot](https://github.com/user-attachments/assets/e8291615-721e-491a-99eb-e13934883d11)

**Comment by luckylyk** [comment]
seems an old picker file. Normally it is supposed to be automatically updated to latest picker format.
could you provide the picker file ?
Pr the maya scene containing the picker ? 
I dont necessaily need the complete scene with rig, ref etc.. Just the maya scene containing the picker data node

**Comment by carlosgmanimacion** [comment]
[dwpicker-main.zip](https://github.com/user-attachments/files/18172992/dwpicker-main.zip)

**Comment by carlosgmanimacion** [comment]
I have the issues in all the scenes. I've created a new scene and I have new errors. (Importing the picker and opening the pickers files)

import dwpicker
dwpicker.show()
DwPicker: could not check for new version
# Traceback (most recent call last):
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\main.py", line 523, in call_open
#     self.add_picker_from_file(filename)
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\main.py", line 465, in add_picker_from_file
#     data = ensure_retro_compatibility(json.load(f))
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\compatibility.py", line 36, in ensure_retro_compatibility
#     update_shape_actions_for_v0_11_0(shape)
#   File "C:\Users/Carlos/Documents/maya/2024/scripts\dwpicker\compatibility.py", line 73, in update_shape_actions_for_v0_11_0
#     if shape['action.left.command']:
# KeyError: 'action.left.command'

**Comment by carlosgmanimacion** [comment]
I can't send you the scene because the web don't support that file type

**Comment by carlosgmanimacion** [comment]
[New scene with the issues.zip](https://github.com/user-attachments/files/18173071/New.scene.with.the.issues.zip)

**Comment by luckylyk** [comment]
Hi,
Opened your scene but does not contains any picker node ?
![image](https://github.com/user-attachments/assets/3d4a9c6e-8fee-4511-963d-2742c33adc0b)

I'm looking for something like this
![image](https://github.com/user-attachments/assets/44b4c9ae-2ec0-46f2-b894-d2a2fbe924cd)

**Comment by carlosgmanimacion** [comment]
I think this is one ofr the problems. It's not installing good. I'm following the text tutorial to install.
[README.md](https://github.com/user-attachments/files/18209687/README.md)

**Comment by luckylyk** [comment]
Hi Carlos,
I'm just back from vacations.
Could you provide the picker file ? just by saving a json ? I should be able to fix it.

**Comment by carlosgmanimacion** [comment]
Hi, sorry I just see it. What is the file you need? The file I downloaded from dream wall picker page in github?

**Comment by luckylyk** [comment]
seems that you are opening a json file (a picker). I can fix it, but need that you send it to me.

**Comment by luckylyk** [comment]
Any news ?

**Comment by luckylyk** [comment]
Without update, I'm closing the ticket. Feel free to reopen if you have more informations
